import { Search } from "lucide-react";
import { Alert, Card, Empty, Input, Space, Tag, Typography } from "antd";

import type { KnowledgeSearchResponse } from "../types";
import styles from "../pages/KnowledgeBasePage.module.css";

const { Search: SearchInput } = Input;

export function KnowledgeBaseSearchPanel({ query, response, loading, error, onQueryChange, onSearch }: { query: string; response?: KnowledgeSearchResponse; loading: boolean; error?: string; onQueryChange: (value: string) => void; onSearch: (value: string) => void }) {
  return <div className={styles.searchWorkspace}><div className={styles.searchIntro}><div className={styles.searchIcon}><Search size={20} /></div><div><Typography.Title level={4}>知识检索</Typography.Title><Typography.Text type="secondary">从已发布的制度知识中找到有依据的答案。</Typography.Text></div></div><Card className={styles.searchForm}><SearchInput size="large" enterButton="检索" placeholder="例如：申请材料需要哪些证明文件？" value={query} onChange={(event) => onQueryChange(event.target.value)} onSearch={onSearch} loading={loading} /><Space wrap className={styles.searchHints}><Typography.Text type="secondary">推荐问题：</Typography.Text><Tag color="processing" onClick={() => onQueryChange("申请材料需要哪些证明文件？")}>申请材料需要哪些证明文件？</Tag><Tag color="processing" onClick={() => onQueryChange("证据不足时应该如何处理？")}>证据不足时应该如何处理？</Tag></Space></Card>{error && <Alert className={styles.searchAlert} type="error" showIcon message={error} />}{response && <div className={styles.resultsHeading}><div><Typography.Text type="secondary">Mock 检索结果</Typography.Text><Typography.Title level={5}>关于“{response.query}”的检索结果</Typography.Title></div><Typography.Text type="secondary">{response.results.length} 个相关片段</Typography.Text></div>}{response ? <div className={styles.resultsList}>{response.results.map((result, index) => <Card className={styles.resultCard} key={result.id}><div className={styles.resultRank}>0{index + 1}</div><div className={styles.resultBody}><Typography.Text type="secondary">{result.source} · {result.section} · {result.page}</Typography.Text><Typography.Title level={5}>{result.title}</Typography.Title><Typography.Paragraph>{result.text}</Typography.Paragraph><Space>{result.tags.map((tag) => <Tag key={tag}>{tag}</Tag>)}</Space></div><Tag color="processing">相关度 {result.score}</Tag></Card>)}</div> : <Empty className={styles.searchEmpty} image={Empty.PRESENTED_IMAGE_SIMPLE} description="输入问题开始检索" />}</div>;
}
