export const UI_TEXT = {
  appEyebrow: "投标文档助手",
  defaultDepartment: "综合管理部",
  defaultCategory: "管理制度",
  requestFailed: "请求失败",
  chooseFileFirst: "请先选择一个要入库的文件。",
  previewFailed: "预览失败。",
  previewFirst: "请先完成预览。",
  ingestFailed: "入库失败。",
  appTitle: "单文件入库工作台",
  appIntro:
    "先选一个文件，完成预览和人工复核，再确认正式入库。这个 MVP 只处理单个文件，方便我们把后端链路一点点跑稳。",
  formTitle: "导入表单",
  formIntro: "上传一次，先预览，再决定是否落库。",
  fileLabel: "待入库文件",
  categoryLabel: "资料分类",
  categoryPlaceholder: "例如：管理制度",
  departmentLabel: "责任部门",
  departmentPlaceholder: "例如：综合管理部",
  versionLabel: "版本标签（可选）",
  versionPlaceholder: "不填时将由后端自动推导",
  currentFile: "当前文件",
  noFileSelected: "尚未选择文件",
  supportedTypes: "支持 .docx / .pdf",
  previewing: "预览中...",
  preview: "先预览",
  ingesting: "入库中...",
  confirmIngest: "确认入库",
  resultTitle: "结果总览",
  resultIntro: "把每个阶段的返回都摊开，方便你核对后端行为。",
  mode: "模式",
  guessedName: "制度名称猜测",
  versionTag: "版本标签",
  sectionCount: "章节数",
  chunkCount: "切块数",
  charCount: "字数",
  none: "无",
  stageStatus: "阶段状态",
  parseNotes: "解析提示",
  noParseNotes: "当前无额外解析备注。",
  cleanNotes: "清洗说明",
  noCleanNotes: "当前无额外清洗说明。",
  removedNoise: "清洗掉的噪音示例",
  noRemovedNoise: "当前没有识别到可删除噪音。",
  titleCandidates: "标题候选",
  noTitleCandidates: "当前没有识别到明显标题。",
  sectionPreview: "章节预览",
  chunkPreview: "切块摘要",
  noChunksYet: "当前还没有切块摘要。",
  chunkStrategy: "切块策略",
  fullText: "全文",
  noSectionPath: "未生成章节路径",
  noSectionsYet: "预览完成后，这里会显示章节拆分结果。",
  persistenceTitle: "入库结果",
  persistenceEmpty: "确认入库后，这里会显示落库结果。",
  noResultsYet: "还没有结果。先选一个文件，然后点“先预览”。",
  documentId: "制度ID",
  versionId: "版本ID",
  versionSeq: "版本序号",
  stageLabels: {
    file_registration: "文件登记",
    intake_validation: "准入校验",
    format_normalization: "格式归一化",
    parse_routing: "解析器选择",
    text_parsing: "文本解析",
    text_cleaning: "文本清洗",
    section_splitting: "章节拆分",
    chunk_splitting: "切块生成",
    embedding_generation: "向量生成",
    chunk_persistence: "切块落库",
    document_persistence: "总体落库",
  },
  statusLabels: {
    pending: "待处理",
    skipped: "已跳过",
    success: "成功",
    failed: "失败",
  },
  modeLabels: {
    preview: "预览",
    ingest: "入库",
  },
  strategyLabels: {
    "section-first-char-window": "章节优先、按字符窗口切块",
    "chapter-article": "按章节条文拆分",
  },
} as const;
