export const UI_TEXT = {
  appEyebrow: "投标文档助手",
  appTitle: "知识库入库与检索工作台",
  appIntro:
    "先把单文件入库链路跑通，再在同一个工作台里调试检索和最小问答，方便我们快速核对知识库行为。",
  ingestionWorkspaceTitle: "单文件入库工作台",
  retrievalWorkspaceTitle: "检索调试台",
  defaultDepartment: "综合管理部",
  defaultCategory: "管理制度",
  requestFailed: "请求失败",
  chooseFileFirst: "请先选择一个要入库的文件。",
  unsupportedFileType: "当前仅支持 .docx / .pdf 文件，请先将 .doc 转换为 .docx 后再上传。",
  previewFailed: "预览失败。",
  previewFirst: "请先完成预览。",
  previewValidationFailed: "当前文件未通过准入校验，不能确认入库。",
  ingestFailed: "入库失败。",
  formTitle: "导入表单",
  formIntro: "上传一次，先预览，再决定是否正式入库。",
  fileLabel: "待入库文件",
  categoryLabel: "资料分类",
  categoryPlaceholder: "例如：管理制度",
  departmentLabel: "责任部门",
  departmentPlaceholder: "例如：综合管理部",
  versionLabel: "版本标签（可选）",
  versionPlaceholder: "不填写时将由后端自动推导",
  targetDocumentLabel: "关联已有制度（可选）",
  targetDocumentSearchPlaceholder: "输入制度名称搜索已有制度",
  targetDocumentEmptyOption: "不指定，由系统按制度名称自动判断",
  currentFile: "当前文件",
  noFileSelected: "尚未选择文件",
  supportedTypes: "仅支持 .docx / .pdf",
  previewing: "预览中...",
  preview: "先预览",
  ingesting: "入库中...",
  confirmIngest: "确认入库",
  resultTitle: "结果总览",
  resultIntro: "把每个阶段的返回直接展开，方便核对后端链路行为。",
  mode: "模式",
  guessedName: "制度名称猜测",
  versionTag: "版本标签",
  sectionCount: "章节数",
  chunkCount: "切块数",
  charCount: "字数",
  none: "无",
  stageStatus: "阶段状态",
  parseNotes: "解析提示",
  noParseNotes: "当前没有额外解析备注。",
  cleanNotes: "清洗说明",
  noCleanNotes: "当前没有额外清洗说明。",
  removedNoise: "清洗掉的噪音示例",
  noRemovedNoise: "当前没有识别到可删除噪音。",
  titleCandidates: "标题候选",
  noTitleCandidates: "当前没有识别到明显标题。",
  sectionPreview: "章节预览",
  chunkPreview: "切块摘要",
  noChunksYet: "当前还没有切块摘要。",
  chunkStrategy: "切块策略",
  fullText: "全文",
  noSectionPath: "未生成章节路径",
  noSectionsYet: "预览完成后，这里会显示章节拆分结果。",
  persistenceTitle: "入库结果",
  persistenceEmpty: "确认入库后，这里会显示落库结果。",
  noResultsYet: "还没有结果。先选择一个文件，然后点击“先预览”。",
  documentId: "制度 ID",
  versionId: "版本 ID",
  versionSeq: "版本序号",
  retrievalTitle: "检索调试",
  retrievalIntro: "使用当前知识库向量链路调试召回结果，也可以直接走最小 GLM 问答。",
  retrievalResultTitle: "检索结果",
  retrievalResultIntro: "这里会展示回答、引用以及召回的原始 chunk，便于定位问题。",
  queryLabel: "查询问题",
  queryPlaceholder: "例如：采购申请需要经过哪些审批环节？",
  queryRequired: "请输入检索问题。",
  topKLabel: "Top K",
  documentIdLabel: "限定制度 ID",
  documentIdPlaceholder: "可选，例如 12",
  includeHistoryLabel: "包含历史版本",
  searching: "检索中...",
  searchOnly: "仅检索",
  asking: "提问中...",
  searchAndAsk: "检索并提问",
  retrievalFailed: "检索失败。",
  answerFailed: "问答失败。",
  answerTitle: "回答",
  citationTitle: "引用列表",
  noCitations: "当前没有可展示的引用。",
  hitListTitle: "召回 chunk 列表",
  noRetrievalResults: "当前没有召回结果。",
  scoreLabel: "分数",
  pageLabel: "页码",
  modelLabel: "模型",
  stageLabels: {
    file_registration: "文件登记",
    intake_validation: "准入校验",
    format_normalization: "格式归一化",
    parse_routing: "解析器选择",
    document_parsing: "文档解析",
    ocr_processing: "OCR 处理",
    text_assembly: "全文组装",
    ingest_guard: "入库拦截",
    text_cleaning: "文本清洗",
    section_splitting: "章节拆分",
    chunk_splitting: "切块生成",
    embedding_generation: "向量生成",
    chunk_persistence: "切块落库",
    document_persistence: "整体落库",
  },
  statusLabels: {
    pending: "待处理",
    skipped: "已跳过",
    success: "成功",
    failed: "失败",
  },
  modeLabels: {
    preview: "预览",
    ingest: "入库",
  },
  strategyLabels: {
    "section-first-char-window": "章节优先，按字符窗口切块",
    "chapter-article": "按章节条文拆分",
  },
} as const;
